regex_patterns:
  object:
    - '\\D'  # Remove non-digit characters for object columns
  float64:
    - '[^\\d.]'  # Remove non-digit characters except dot for float columns
  int64:
    - '\\D'  # Remove non-digit characters for int columns
  datetime64[ns]:
    - '.*'  # Replace all content in datetime columns
  bool:
    - 'False'  # Remove 'False' for boolean columns

scan_patterns:
  #- '\d+'         # Regex to find any digit
  #- "[a-z]"       # Regex to find any lowercase letter
  #- "(\\d{3}|\\(\\d{3}\\))(:?\\s+|-|\\.)?(\\d{3})(:?\\s+|-|\\.)?(\\d{4})"
  - "(\\d{3}|\\(\\d{3}\\))(:?\\s+|-|\\.)?(\\d{3})(:?\\s+|-|\\.)?(\\d{4})"

dev:
  elasticsearch_url: "http://localhost:9200"
  csv_output_path: "output_dev"

test:
  elasticsearch_url: "http://test-es:9200"
  csv_output_path: "output_test"

prod:
  elasticsearch_url: "https://prod-es:9200"
  csv_output_path: "output_prod"
